'use strict';
const projects = [
{name:'TechCore · Ventas',label:'HENRY / MÓDULO 3',category:'bi',tags:['Power BI','DAX','Python'],description:'De ventas sin transformar a un modelo relacional y un informe de negocio.',problem:'Analizar ventas por producto, cliente, vendedor y sucursal manteniendo el contexto de filtros.',approach:'Limpieza con Power Query, modelado en Python y dashboard Power BI con seguridad por roles documentada.',evidence:['CSV original y transformado.','Notebook de modelado y workbook del modelo.','Dos archivos PBIX y documentación del informe de nueve páginas.'],note:'Proyecto académico. El costo del 65 % y el margen del 35 % se documentan como supuestos simulados, no como rentabilidad observada.',url:'@techcore'},
{name:'Bank Transactions',label:'PERSONAL / POWER BI',category:'bi',tags:['Power BI','Power Query','DAX'],description:'Más de un millón de registros organizados por fecha, sector y ubicación.',problem:'Distinguir cantidad de registros, transacciones y valor para comparar sectores y ubicaciones.',approach:'Modelo con tabla de hechos y dimensiones en copo de nieve; reporte PBIP editable y validación de integridad de los CSV.',evidence:['1.004.480 identificadores de hechos únicos.','0 valores nulos en la tabla de hechos.','0 claves huérfanas de fecha, sector y ubicación.','Vista web calculada a partir de los CSV.'],note:'Moneda y origen institucional no especificados. Las cifras son agregados del dataset proporcionado.',url:'@bank'},
{name:'Churn Intelligence',label:'NO COUNTRY / EQUIPO 40',category:'ml',tags:['XGBoost','Streamlit','Supabase'],description:'Análisis y predicción del abandono de clientes en comercio electrónico.',problem:'Identificar clientes con riesgo de abandono a partir de su comportamiento de compra.',approach:'El repositorio documenta segmentación RFM, etiquetado de churn, modelos y un dashboard.',evidence:['Notebooks de exploración, ingeniería de características y modelado.','Pipelines de entrenamiento e inferencia.','Pruebas unitarias y documentación de métricas.'],note:'Proyecto en equipo; repositorio derivado mediante fork. Las métricas del README no se han reentrenado en esta revisión.',url:'-E-commerce-Churn-Model-S03-26-Equipo-40-Data-Science'},
{name:'EquineLead',label:'NO COUNTRY / EQUIPO 45',category:'ml',tags:['Python','XGBoost','Streamlit'],description:'Analítica y priorización de leads en el mercado ecuestre.',problem:'Explorar el comportamiento de visitantes y priorizar oportunidades comerciales.',approach:'Sistema en equipo con pipelines, modelos y dashboard. El README del equipo identifica a Dody como Data Analyst.',evidence:['Módulos de analítica de audiencia y conversión.','Documentación del pipeline y de las fuentes.','Autoría y roles del equipo publicados.'],note:'La arquitectura y los modelos pertenecen al proyecto colectivo. El rol individual documentado es Data Analyst.',url:'S02-26-E45-Data_Science_EquineLead'},
{name:'LatAm Insights',label:'NO COUNTRY / MERCADO LABORAL',category:'bi',tags:['Python','Streamlit','Supabase'],description:'Exploración del mercado laboral a partir de vacantes y habilidades.',problem:'Organizar información de ofertas para entender perfiles y habilidades demandados.',approach:'Extracción, procesamiento y visualización; el repositorio documenta spiders y conexiones a Supabase.',evidence:['Código Python del proyecto.','Documentación de ejecución y configuración.','Integración de análisis y visualización.'],note:'La ejecución de extracción depende del acceso a fuentes externas y de sus condiciones de uso.',url:'Proyecto-No-Country'},
{name:'FleetLogix',label:'HENRY / MÓDULO 2',category:'engineering',tags:['PostgreSQL','Snowflake','Python'],description:'Modelado y procesamiento de datos sintéticos para analítica logística.',problem:'Conectar datos operativos de rutas, vehículos y entregas con indicadores logísticos.',approach:'Generadores de datos, ETL, bases relacionales y consultas analíticas; componentes AWS descritos como simulación.',evidence:['Generadores por entidad de negocio.','Consultas SQL y scripts de exportación.','Documentación del modelo y los KPIs.'],note:'Proyecto de formación con datos sintéticos. No equivale a una implementación empresarial en operación.',url:'FleetLogix-Master'},
{name:'Cliente360',label:'HENRY / PROYECTO INTEGRADOR',category:'ml',tags:['pandas','scikit-learn','Python'],description:'Segmentación de clientes y análisis de oportunidades de mercado.',problem:'Relacionar características de clientes y contexto del mercado con decisiones de segmentación.',approach:'ETL, características, regresión, clustering y reportes de análisis.',evidence:['Notebooks por etapa del pipeline.','Tablas procesadas y comparación de modelos.','Figuras e informe ejecutivo publicados.'],note:'Proyecto académico; las recomendaciones representan análisis del dataset, no impacto comercial medido.',image:'https://raw.githubusercontent.com/dodysalim/Cliente360-Predictive-Insight/main/reports/figures/15_executive_dashboard.png',url:'Cliente360-Predictive-Insight'},
{name:'Riesgo crediticio',label:'HENRY / MÓDULO 5',category:'ml',tags:['Python','ML','MLOps'],description:'Pipeline de análisis y predicción de riesgo crediticio.',problem:'Estudiar características asociadas al incumplimiento y evaluar un modelo predictivo.',approach:'Exploración, preparación de características y evaluación según la documentación del proyecto M5.',evidence:['Repositorio del proyecto integrador.','Diccionario de datos y metodología documentada.','Secciones de evaluación y despliegue.'],note:'Proyecto de formación. La evaluación requiere revisar partición, fuga de información y reproducibilidad antes de un uso operativo.',url:'Proyecto_Integrador_M5'},
{name:'Analytics Toolkit',label:'PERSONAL / HERRAMIENTAS',category:'engineering',tags:['Python','SQL','Streamlit'],description:'Módulos de análisis, limpieza y visualización reutilizables.',problem:'Organizar tareas frecuentes de análisis de datos en componentes reutilizables.',approach:'Módulos de calidad, evaluación, series temporales y análisis estadístico, con dashboard en src/app.',evidence:['Código de módulos y patrones.','Notebooks de exploración y consultas SQL.','Aplicación Streamlit organizada por vistas.'],note:'La utilidad de cada módulo se evalúa con sus entradas y dependencias; no se afirma cobertura de pruebas global.',url:'data-science-analytics-toolkit'},
{name:'KrioMetrics',label:'PERSONAL / REFRIGERACIÓN',category:'bi',tags:['Python','SQLite','Streamlit'],description:'Analítica de propiedades y comparación de gases refrigerantes.',problem:'Explorar propiedades de refrigerantes mediante un pipeline y visualizaciones.',approach:'ETL, almacenamiento y dashboards descritos en el repositorio.',evidence:['Notebooks y código de análisis.','Datos y recursos de refrigerantes.','Workflows y pruebas publicados.'],note:'Proyecto analítico; los valores y modelos requieren consultar sus fuentes antes de aplicaciones de ingeniería.',url:'refrigerant-gas-dashboard'},
{name:'Simpson 1/3',label:'PERSONAL / EXCEL VBA',category:'engineering',tags:['Excel','VBA','Cálculo'],description:'Cálculo y visualización de integrales definidas con integración numérica.',problem:'Aproximar integrales y mostrar la curva y la tabla de evaluación.',approach:'Libro Excel con macros y código VBA publicado para el método de Simpson 1/3.',evidence:['Simpson_Pro.xlsm en el repositorio.','Código VBA separado.','Documentación del método y la interfaz.'],note:'Requiere Excel con macros y un número par de subintervalos. Este es el proyecto matemático localizado en GitHub.',url:'Simpson-13-Dashboard-Excel'}
];
const origin = p => p.label.startsWith('HENRY') ? 'henry' : p.label.startsWith('NO COUNTRY') ? 'nocountry' : 'personal';
const repoUrl = p => p.url === '@techcore' ? 'https://github.com/dodysalim/xd/tree/main/projects/techcore-sales-powerbi' : p.url === '@bank' ? 'https://github.com/dodysalim/xd/tree/main/projects/bank-transactions-powerbi' : 'https://github.com/dodysalim/' + p.url;
const grid=document.getElementById('project-grid');
function renderProjects(filter='all'){grid.replaceChildren();projects.forEach((p,i)=>{if(filter!=='all'&&origin(p)!==filter)return;const article=document.createElement('article');article.className='project-card';article.innerHTML=`<div class="card-top"><span>${p.label}</span><span>${String(i+1).padStart(2,'0')}</span></div><h3>${p.name}</h3><p>${p.description}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><div class="card-actions"><button data-project="${i}">Ver caso</button>${p.url?`<a href="${repoUrl(p)}" target="_blank" rel="noopener">Repositorio</a>`:'<span>Archivos del autor</span>'}</div>`;grid.append(article);translateTree(article);});}
renderProjects();document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});renderProjects(button.dataset.filter);}));
const dialog=document.getElementById('project-dialog');grid.addEventListener('click',e=>{const button=e.target.closest('[data-project]');if(!button)return;const p=projects[Number(button.dataset.project)];document.getElementById('project-detail').innerHTML=`<p class="eyebrow">${p.label}</p><h2>${p.name}</h2><h3>Problema</h3><p>${p.problem}</p><h3>Enfoque</h3><p>${p.approach}</p><h3>Evidencia disponible</h3><ul>${p.evidence.map(t=>`<li>${t}</li>`).join('')}</ul>${p.image?`<img src="${p.image}" alt="Informe ejecutivo del proyecto Cliente360" loading="lazy">`:''}<h3>Contexto y alcance</h3><p>${p.note}</p>${p.url?`<a class="button" href="${repoUrl(p)}" target="_blank" rel="noopener">Abrir repositorio</a>`:''}`;translateTree(dialog);dialog.showModal();});dialog.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
let bank;const number=n=>new Intl.NumberFormat(document.documentElement.lang === 'en' ? 'en-US' : 'es-EC',{maximumFractionDigits:0}).format(n);const decimal=n=>new Intl.NumberFormat(document.documentElement.lang === 'en' ? 'en-US' : 'es-EC',{maximumFractionDigits:2}).format(n);
fetch('bank-data.json').then(r=>{if(!r.ok)throw Error('data');return r.json();}).then(data=>{bank=data;for(const name of ['domain','location']){const select=document.getElementById(name);data[name+'s'].forEach(t=>{const o=document.createElement('option');o.value=t;o.textContent=t;select.append(o);});select.addEventListener('change',updateAnalysis);}document.getElementById('metric').addEventListener('change',updateAnalysis);updateAnalysis();}).catch(()=>{document.getElementById('chart-title').textContent='No se pudieron cargar los datos. Recarga la página.';});
function updateAnalysis(){if(!bank)return;const domain=document.getElementById('domain').value,location=document.getElementById('location').value,metric=document.getElementById('metric').value;const selected=bank.rows.filter(r=>(domain==='all'||r.domain===domain)&&(location==='all'||r.location===location));const monthly=new Map();let rows=0,transactions=0,value=0;for(const r of selected){rows+=r.records;transactions+=r.Transaction_count;value+=r.Value;const m=monthly.get(r.month)||{month:r.month,Value:0,Transaction_count:0};m.Value+=r.Value;m.Transaction_count+=r.Transaction_count;monthly.set(r.month,m);}document.getElementById('rows').textContent=number(rows);document.getElementById('transactions').textContent=number(transactions);document.getElementById('value').textContent=number(value);document.getElementById('average').textContent=transactions?decimal(value/transactions):'—';const series=[...monthly.values()].sort((a,b)=>a.month.localeCompare(b.month));document.getElementById('chart-title').textContent=metric==='Value'?'Valor agregado por mes':'Transacciones por mes';document.getElementById('monthly-table').innerHTML=series.map(r=>`<tr><th scope="row">${r.month}</th><td>${number(r.Transaction_count)}</td><td>${number(r.Value)}</td></tr>`).join('');translateTree(document.getElementById('chart-title'));drawChart(series,metric);}
function drawChart(series,metric){const c=document.getElementById('chart'),ratio=window.devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*ratio;c.height=h*ratio;const ctx=c.getContext('2d');ctx.scale(ratio,ratio);const left=60,right=20,top=20,bottom=42,max=Math.max(...series.map(r=>r[metric]),1)*1.12;ctx.font='12px system-ui';ctx.fillStyle='#a7b5ce';ctx.strokeStyle='#293449';for(let i=0;i<=4;i++){const y=top+(h-top-bottom)*i/4;ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(w-right,y);ctx.stroke();ctx.fillText(new Intl.NumberFormat(document.documentElement.lang,{notation:'compact',maximumFractionDigits:1}).format(max*(1-i/4)),2,y+4);}const step=(w-left-right)/Math.max(series.length,1);series.forEach((r,i)=>{const bh=r[metric]/max*(h-top-bottom),bw=Math.max(step*.65,1),x=left+step*i+step*.18;ctx.fillStyle='#75e6ce';ctx.fillRect(x,h-bottom-bh,bw,bh);if(w>550||i%2===0){ctx.fillStyle='#a7b5ce';ctx.textAlign='center';ctx.fillText(r.month.slice(5),x+bw/2,h-bottom+24);ctx.textAlign='left';}});c.setAttribute('aria-label',`${document.getElementById('chart-title').textContent}; ${series.length} meses. Valores exactos en la tabla.`);}
window.addEventListener('resize',()=>updateAnalysis());

window.addEventListener('portfolio-language',()=>{renderProjects(document.querySelector('[data-filter].active').dataset.filter);dialog.close();updateAnalysis();});
